### ISSUE TITLE
Notification log

### ISSUE THREAD

**Issue by keivanshahida** [cuappdev/tempo-backend#30]
For the purpose of developing a notification center for users to view all relevant activity.

**Comment by jk2227** [comment]
https://github.com/cuappdev/tempo-backend/pull/31

**Comment by jk2227** [comment]
get 'notifications/:user_id' => 'notifications#getNotifications'

put 'notifications/:notification_id' => 'notifications#seen' 

Let me know if anything else is needed @loganallen
